- hosts: centos1
  tasks: 
  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Install apace
    yum:
      name: httpd
      state: latest

  - name: Make sure service is running
    systemd:
      state: started
      enabled: yes
      name: httpd

  - name: Download foo.conf
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page294/primecare.zip
      dest: /tmp/

  - name: Install unzip
    yum:
      name: unzip
      state: latest     

  - name: Unarchive a file that is already on the remote machine
    unarchive:
      src: /tmp/primecare.zip
      dest: /var/www/html
      remote_src: yes     

  - name: Move template Files 
    shell: mv /var/www/html/primecare-html/*  /var/www/html/
    args:
      creates: /var/www/html/index.html

  - name: Recursively change ownership of a directory
    file:
      path: /var/www/html
      state: directory
      recurse: yes
      owner: apache
      group: apache
